const products = [
  { id: 1, name: "Summer Dress", price: 1499, image: "assets/images/dress.png", description: "A breezy charm that brings sunshine to your every step." },
  { id: 2, name: "Chikankari Kurti", price: 999, image: "assets/images/kurti.jpg", description: "Intricate threads that weave grace into your everyday." },
  { id: 3, name: "Silk Saree", price: 2599, image: "assets/images/saree.png", description: "Flowing elegance draped in timeless silk." },
  { id: 4, name: "Western Wear", price: 1799, image: "assets/images/western wear.png", description: "Modern style for the confident soul." },
  { id: 5, name: "Yellow Kurti", price: 899, image: "assets/images/kurti set2.png", description: "A sunny delight that brightens every room." },
  { id: 6, name: "Black Western Wear", price: 2899, image: "assets/images/western wear1.png", description: "Bold, sleek, and effortlessly chic." },
  { id: 7, name: "Elegent Wear", price: 1999, image: "assets/images/elegent wear.png", description: "Subtle sophistication that speaks volumes." },
  { id: 8, name: "Kurti Set", price: 1499, image: "assets/images/kurtiset3.png", description: "Comfort and style entwined in perfect harmony." },
  { id: 9, name: "Top", price: 499, image: "assets/images/top.png", description: "Simple charm for effortless days." },
  { id: 10, name: "Simple T", price: 399, image: "assets/images/t.png", description: "Casual ease wrapped in understated elegance." },
  { id: 11, name: "White Printed Kurti Set", price: 1499, image: "assets/images/kurti set.png", description: "Fresh patterns that whisper pure elegance." },
  { id: 12, name: "T-Shirts", price: 1299, image: "assets/images/t-shirts.png", description: "Everyday comfort with a stylish twist." },
  { id: 13, name: "Jacket", price: 1199, image: "assets/images/jacket.png", description: "Warmth and style in a single embrace." },
  { id: 14, name: "Red Blazer", price: 1599, image: "assets/images/coat.png", description: "Confidence painted in vibrant red." },
  { id: 15, name: "Colourful Kurti Set", price: 1599, image: "assets/images/kurti set 4.png", description: "A lively palette for joyful days." },
  { id: 16, name: "Grey Kurti Set", price: 1599, image: "assets/images/kurti set 5.png", description: "Neutral elegance that never fades." },
  { id: 17, name: "White Dress", price: 2199, image: "assets/images/white dress2.png", description: "Purity and grace woven into every fold." },
  { id: 18, name: "Pink Satin Coat", price: 1299, image: "assets/images/coat2.png", description: "Soft glamour that turns heads." },
  { id: 19, name: "Saree", price: 3599, image: "assets/images/saree1.png", description: "Classic drapes for timeless beauty." },
  { id: 20, name: "Kurti Set", price: 1299, image: "assets/images/kurti set 6.png", description: "Chic simplicity for every moment." },
  { id: 21, name: "Yellow Dress", price: 1799, image: "assets/images/dress3.png", description: "Sunlit joy captured in a dress." },
  { id: 22, name: "Western wear", price: 1599, image: "assets/images/western wear2.png", description: "Urban flair for modern adventures." },
  { id: 23, name: "Kurti Set", price: 1199, image: "assets/images/kurti set7.png", description: "Delicate charm with everyday grace." },
  { id: 24, name: "Coat", price: 1599, image: "assets/images/coat3.png", description: "Elegant warmth that complements any outfit." },
  { id: 25, name: "Black Jacket", price: 2199, image: "assets/images/jacket1.png", description: "A sleek statement of confidence." },
  { id: 26, name: "Kurti Set", price: 1299, image: "assets/images/kurti set8.png", description: "Refined style for relaxed moments." },
  { id: 27, name: "Purple Silk Saree", price: 2599, image: "assets/images/saree2.png", description: "Regal hues flowing with grace." },
  { id: 28, name: "Black Leather Jacket", price: 3599, image: "assets/images/jacket2.jpg", description: "Bold and daring for the fearless." },
  { id: 29, name: "Jacket", price: 1799, image: "assets/images/Yellow jacket3.png", description: "Vibrant energy stitched to perfection." },
  { id: 30, name: "Dress", price: 2599, image: "assets/images/dress4.png", description: "Elegance that dances with the breeze." },
  { id: 31, name: "Kurti Set", price: 1299, image: "assets/images/kurti set9.png", description: "Comfort and charm in one ensemble." },
  { id: 32, name: "Saree", price: 1599, image: "assets/images/saree3.png", description: "Graceful folds that tell a story." },
  { id: 33, name: "Maroon Coat", price: 1799, image: "assets/images/coat4.png", description: "Rich tones for a confident stride." },
  { id: 34, name: "Kurti Set", price: 1599, image: "assets/images/kurti set10.png", description: "Everyday elegance with effortless charm." },
  { id: 35, name: "White Dress", price: 1799, image: "assets/images/dress5.png", description: "Timeless beauty in crisp white." },
  { id: 36, name: "Green Straightcut Kurti Set", price: 1599, image: "assets/images/kurti set11.png", description: "Fresh hues for a lively presence." },
  { id: 37, name: "Brown Coat", price: 2599, image: "assets/images/coat5.png", description: "Earthy elegance for all seasons." },
  { id: 38, name: "Kurti Set", price: 1599, image: "assets/images/kurti set12.png", description: "Graceful layers for casual sophistication." },
  { id: 39, name: "Silk Saree", price: 2399, image: "assets/images/saree4.png", description: "Luxurious silk that flows like poetry." },
  { id: 40, name: "Black Silk Saree", price: 2599, image: "assets/images/saree5.png", description: "Classic elegance in deep midnight tones." }
];
